### ISSUE TITLE
Preserving the ID of the source image

### ISSUE THREAD

**Issue by SuperKXT** [HiDeoo/starlight-image-zoom#38]
### Is your feature request related to a problem?

This is a little silly, but I am using CSS filters to improve the mermaid diagram images for dark modes.

I select the images where the id has the mermaid prefix.
```css
:root:not([data-theme="light"]) img[id^="mermaid-"] {
	filter: invert(1);
}
```

This breaks with the plugin since the zoomed image does not have the ID.

### Describe the solution you'd like

Adding an ID to the zoomed image that uses the original image's ID should work.
